language: c
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libssl-dev check
before_script:
    - mkdir build
    - cd build
    - cmake ..
script:
    - ctest --output-on-failure
compiler:
  - clang
  - gcc