language: c
env:
    global:
        - CFLAGS=-Werror -Wno-error=unused-value
        - MODULE_PATH=/usr/lib/libsofthsm.so
        - ENGINE_PATH=/usr/lib/engines/engine_pkcs11.so
before_install:
    - sudo apt-get install python-software-properties
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    - sudo apt-get install -y libssl-dev check liburiparser-dev libcurl4-openssl-dev gcc-4.8 softhsm libp11-dev
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
install:
    - wget http://sourceforge.net/projects/opensc/files/engine_pkcs11/engine_pkcs11-0.1.8.tar.gz/download -O /tmp/engine_pkcs11-0.1.8.tar.gz
    - cd /tmp && tar -xzf /tmp/engine_pkcs11-0.1.8.tar.gz && cd -
    - cd /tmp/engine_pkcs11-0.1.8 &&  ./configure --prefix=/usr && make && sudo make install && cd -
before_script:
    - mkdir build
    - cd build
    - cmake ..
    - gcc --version
    - make VERBOSE=1
script: ctest --output-on-failure
compiler:
  - gcc