language: c
env:
    global:
        - CFLAGS="-Werror -Wno-error=unused-value"
before_install:
    - sudo apt-get install python-software-properties
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    - sudo apt-get install -y libssl-dev check liburiparser-dev libcurl4-openssl-dev gcc-4.8 softhsm libp11-dev
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
before_script:
    - mkdir build
    - cd build
    - cmake .. -DWITH_ENGINE_TESTS=yes
    - make build_test VERBOSE=1
script: ctest --output-on-failure
compiler:
  - gcc